name: Deployment
on:
    push:
        branches:
            - master

env:
    CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
    CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
    APP_DIR: ${{ secrets.APP_DIR }}

jobs:
    deployment:
        runs-on: ubuntu-latest
        environment:
            name: test
            url: https://app-f2639bd0-2ade-41f5-b2c3-33c3b6303a27.cleverapps.io/
        steps:
            -   uses: actions/checkout@v2
            -   name: Install clever-tools
                run: npm install -g clever-tools
            -   name: Deploy
                run: |
                    mkdir -p ~/deployment
                    rm -rf .git
                    cp .clever.json ~/deployment/
                    cp -r clevercloud  ~/deployment/
                    cd $APP_DIR && tar cvzf ~/deployment/artifact.tgz ./
                    cd ~/deployment
                    git config --global user.email "madamebiz@monsieurbiz.com"
                    git config --global user.name "Madame Biz"
                    git init
                    git add -A
                    git commit -m "Deploy ${{ github.GITHUB_SHA }}"
                    clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
                    clever deploy --force
                    
