name: Deployment
on:
    push:
        branches:
            - master

jobs:
    deployment:
        runs-on: ubuntu-latest
        environment:
            name: test
            url: ${{ secrets.CLEVER_URL }}
        steps:
            -   uses: actions/checkout@v2
            -   name: Install clever-tools
                run: npm install -g clever-tools
            -   name: Deploy
                run: |
                    mkdir -p ~/deployment
                    rm -rf .git
                    cp .clever.json ~/deployment/
                    cp -r clevercloud  ~/deployment/
                    cd ${{ secrets.CLEVER_DIR }} && tar cvzf ~/deployment/artifact.tgz ./
                    cd ~/deployment
                    git config --global user.email "madamebiz@monsieurbiz.com"
                    git config --global user.name "Madame Biz"
                    git init
                    git add -A
                    git commit -m "Deploy ${{ env.GITHUB_SHA }}"
                    clever login --token ${{ secrets.CLEVER_TOKEN}} --secret ${{ secrets.CLEVER_SECRET }}
                    clever deploy --force
                    
